version: '3.8'

services:
  nginx:
    image: local-nginx
    ports:
      - "80:80"  # Correctly mapping port 80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf  # Correct volume mapping
    networks:
      - nginx-network

  python-app:
    image: local-python-app
    container_name: python-app-service
    expose:
      - "8000"  # Correctly exposing port 8000
    networks:
      - nginx-network

networks:
  nginx-network:
    driver: bridge  # Correct network driver
